### ISSUE TITLE
Blog posts should have metadata

### ISSUE THREAD

**Issue by chothia** [debonairio/website#3]
Hi Nathan,

Excellent work on your blog post.

I need to update the readme, and so I forgot to mention that you should add metadata to each post.

For example, add something like this to the top of your post(s)

+++
date = "2014-11-05T01:21:00-07:00"
title = "The Debonair Stack  - Part 2 : Reintroduction"
tags = ["stylish-stacks"]
author = "brandon"
+++

If you visit the website http://www.debonair.io you'll notice that your post doesn't have a title or date.

Thanks

**Comment by chothia** [comment]
@kag0 Can this be closed?

**Comment by nrktkt** [comment]
verily
